// Generated by Finicky Kickstart 
// Save as ~/.finicky.js

module.exports = {
  defaultBrowser: "Firefox",      
  handlers: [
    {
      match: /^https?:\/\/meet\.google\.com\/.*$/,
      browser: "Google Chrome Canary"
    },
    {
      match: /^https?:\/\/zoom\.us\/.*$/,
      browser: "us.zoom.xos"
    },
    {
      match: /^https?:\/\/localhost:.*$/,
      browser: "Firefox Developer Edition"
    },
    {
      match: /^https?:\/\/.*intra\.vincit\.fi\/.*$/,
      browser: "Google Chrome Canary"
    },
  ]
}
