'$schema' = 'https://jj-vcs.github.io/jj/latest/config-schema.json'

[aliases]
bc  = { doc = 'create bookmark set to last commit',             definition = ['bookmark', 'create', '-r', '@-'] }
c   = { doc = 'commit',                                         definition = ['commit'] }
d   = { doc = 'diff',                                           definition = ['diff'] }
ds  = { doc = 'diff split',                                     definition = ['diff', '--config', 'merge-tools.delta.diff-args=["-s", "$left", "$right", "--width=$width"]'] }
du  = { doc = 'diff unified',                                   definition = ['diff', '--config', 'merge-tools.delta.diff-args=["$left", "$right", "--width=$width"]'] }
f   = { doc = 'fetch from git repo',                            definition = ['git', 'fetch'] }
l   = { doc = 'list all tracked commits',                       definition = ['log', '-r', 'present(@) | ancestors(immutable_heads().., 2) | trunk()'] }
la  = { doc = 'list ALL commits',                               definition = ['log', '-r', 'all()']}
nt  = { doc = 'new commit based off of `trunk()`',              definition = ['new', 'trunk()'] }
p   = { doc = 'push to git repo',                               definition = ['git', 'push'] }
s   = { doc = 'status',                                         definition = ['status'] }
sr  = { doc = 'squash @- into @--',                             definition = ['squash', '-f', '@-', '-t', '@--'] }
sp  = { doc = 'split',                                          definition = ['split'] }
st =  { doc = 'status for revision',                            definition = ['diff', '-s', '-r'] }
rt  = { doc = 'rebase current branch or revset onto `trunk()`', definition = ['rebase', '-o', 'trunk()'] }
rta = { doc = 'rebase ALL bookmarks onto `trunk()`',            definition = ['rebase', '-o', 'trunk()', '-s', 'fork_point(bookmarks())+ & ::bookmarks()'] }
tug = { doc = 'pull closest bookmark up to latest commit',      definition = ['bookmark', 'advance', '-t', '@-'] }

[ui]
default-command = ['log', '-r', '(trunk()..@):: | (trunk()..@)-']
diff-formatter = ["difft", "--color=always", "$left", "$right"]

[merge-tools.delta]
diff-expected-exit-codes = [0, 1]
diff-args = ["--side-by-side", "$left", "$right", "--width=$width"]

[colors]
change_id = 'bright red'
bookmark = 'bright red'
bookmarks = 'bright red'
local_bookmarks = 'bright red'
remote_bookmarks = 'bright red'
'working_copy change_id' = 'bright red'
'working_copy bookmark' = 'bright red'
'working_copy bookmarks' = 'bright red'
'working_copy local_bookmarks' = 'bright red'
'working_copy remote_bookmarks' = 'bright red'

[templates]
draft_commit_description = '''
concat(
  builtin_draft_commit_description,
  "\nJJ: ignore-rest\n",
  diff.git(),
)
'''

[user]
name = 'Ben Smith'
email = 'ben@bensmith.sh'
