# shellcheck disable=2148
# vim: ft=sh
brew "bat"
brew "cloc"
brew "curlie"
brew "datasette"
brew "difftastic"
brew "exa"
brew "fd"
brew "fzf"
brew "gh"
brew "git-delta"
brew "httpie"
# https://sr.ht/~gpanders/ijq/ 
brew "ijq"
brew "jq"
brew "jesseduffield/lazygit/lazygit"
brew "litecli"
brew "lua-language-server"
brew "luv"
brew "micro"
brew "node"
brew "nodenv"
# brew "ncspot"
brew "pandoc"
brew "pgcli"
brew "ripgrep"
brew "shellcheck"
brew "streamlink"
brew "stylua"
brew "tldr"
brew "tmux"
brew "youtube-dl"
brew "zk"
