#!/bin/sh

# set up key rebindings
# xcape -e "Super_L=Escape;Super_R=Return;Shift_L=Shift_L|braceleft;Shift_R=Shift_R|braceright" &

# set cursor type
xsetroot -cursor_name arrow &

# set key repeat delay
xset r rate 250 25 &

# disabled airpods from connecting automatically
# bluetoothctl disconnect E8:85:4B:4A:82:86; bluetoothctl block E8:85:4B:4A:82:86 &

# set imwheel to autostart
systemctl --user restart imwheel.service
