#!/bin/sh

# ~/.xinitrc

sh -c "~/dotfiles/config/displays.sh"
xcape -e "Super_L=Escape;Super_R=Return" &
xsetroot -cursor_name arrow &
xss-lock i3lock -- -c 27212e &
picom -b &
flameshot &
nm-applet &

exec dbus-launch $@

# dbus-update-activation-environment --systemd DBUS_SESSION_BUS_ADDRESS DISPLAY XAUTHORITY &
# exec dbus-launch --autolaunch=$(cat /var/lib/dbus/machine-id) awesome
