#!/bin/sh
# ~/.xinitrc

# load xrandr setup for displays
sh -c "~/dotfiles/config/displays.sh"

# set up key rebindings
xcape -e "Super_L=Escape;Super_R=Return;Shift_L=Shift_L|braceleft;Shift_R=Shift_R|braceright" &

# set cursor type
xsetroot -cursor_name arrow &

# set key repeat delay
xset r rate 250 25 &

# set up auto-locking of screen
xss-lock i3lock -- -c 27212e &

# launch compositor
picom -b &

# launch screenshot utility
flameshot &

# launch network utility
nm-applet &

# launch the proper window manager with dbus
exec dbus-launch $@

# dbus-update-activation-environment --systemd DBUS_SESSION_BUS_ADDRESS DISPLAY XAUTHORITY &
# exec dbus-launch --autolaunch=$(cat /var/lib/dbus/machine-id) awesome
