default_keybindings = true
use_nerdfont = true
audio_cache = true
volnorm = true
bitrate = 320
album_column = true
cover_max_scale = 2
gapless = false
command_key = ":"
initial_screen = "library"

[saved_state]
volume = 100
shuffle = "playlist"
notify = false
repeat = true

[keybindings]
"," = "queue"
"." = "playnext"
"?" = "help"
"]" = "volup 5"
"[" = "voldown 5"
"+" = "volup 1"
"-" = "voldown 1"
"1" = "sort added descending"
"2" = "sort artist ascending"
"3" = "sort artist descending"

"a" = "goto album"
"b" = "seek -1000"
"f" = "seek +1000"
"g" = "move top"
"h" = "move left 1"
"j" = "move down 1"
"k" = "move up 1"
"l" = "move right 1"
"o" = "open selected"
"p" = "playpause"
"q" = "back"
"r" = "reload"
"s" = "shuffle"
"x" = "share current"
"Space" = "playpause"
"Enter" = "play"

"Shift+a" = "goto artist"
"Shift+b" = "seek -10000"
"Shift+c" = "clear"
"Shift+d" = "delete"
"Shift+f" = "seek +10000"
"Shift+h" = "previous"
"Shift+j" = "shift down 1"
"Shift+k" = "shift up 1"
"Shift+g" = "move bottom"
"Shift+l" = "next"
"Shift+s" = "save"
"Shift+u" = "update"

"Ctrl+a" = "focus cover"
"Ctrl+b" = "move up 10"
"Ctrl+c" = "quit"
"Ctrl+d" = "move down 5"
"Ctrl+f" = "move down 10"
"Ctrl+j" = "shift down 5"
"Ctrl+k" = "shift up 5"
"Ctrl+l" = "focus library"
"Ctrl+o" = "open current"
"Ctrl+p" = "move playing"
"Ctrl+q" = "focus queue"
"Ctrl+r" = "repeat"
"Ctrl+s" = "focus search"
"Ctrl+u" = "move up 5"
"Ctrl+v" = "insert"
"Ctrl+x" = "share selected"

[theme]
# TOKYO NIGHT theme using terminal's colors
background = "default"
primary = "light white"
secondary = "blue"
title = "green"
playing = "#181818"
playing_selected = "#181818"
playing_bg = "red"
highlight = "#181818"
highlight_bg = "blue"
error = "#181818"
error_bg = "yellow"
statusbar = "#181818"
statusbar_progress = "green"
statusbar_bg = "red"
cmdline = "#181818"
cmdline_bg = "red"
search_match = "light yellow"

# LASERWAVE theme using terminal's colors
# background = "default"
# primary = "white"
# secondary = "blue"
# title = "blue"
# playing = "black"
# playing_selected = "black"
# playing_bg = "#40b4c4"
# highlight = "black"
# highlight_bg = "yellow"
# error = "black"
# error_bg = "red"
# statusbar = "black"
# statusbar_progress = "yellow"
# statusbar_bg = "blue"
# cmdline = "black"
# cmdline_bg = "#40b4c4"
# search_match = "#40b4c4"

# config with hexes (broken in ncspot at the moment)
# background = "default"
# primary = "#e0dfe1"
# secondary = "#74dfc4"
# title = "#74dfc4"
# playing = "#222222"
# playing_selected = "#222222"
# playing_bg = "#40b4c4"
# highlight = "#222222"
# highlight_bg = "#eb64b9"
# error = "#222222"
# error_bg = "#ffe261"
# statusbar = "#222222"
# statusbar_progress = "#eb64b9"
# statusbar_bg = "#74dfc4"
# cmdline = "#222222"
# cmdline_bg = "#40b4c4"
# search_match = "#40b4c4"
