eq_preset = "Pop"
# initial_directory = "~/music"
provider = "navidrome"
repeat = "all"
shuffle = false
theme = ""
# visualizer = "BarsDot"
visualizer = "None"

eq = [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[navidrome]
browse_sort = "alphabeticalByArtist"
