#!/bin/sh
# generated by `arandr` program
# pop_os vincit laptop + main monitor
# --output eDP-1-1 --off \

xrandr --output eDP-1-1 --mode 1920x1080 --pos 0x0 --rotate normal --rate 144.03 \
  --output HDMI-0 --primary --mode 1920x1080 --pos 1920x0 --rotate normal --rate 144.00
