require('colorizer').setup {
  filetypes = {
    'css',
    'less',
    'sass',
    'scss',
    'stylus',
    -- '*',
    -- '!TelescopePrompt',
    -- '!TelescopeResults',
    -- '!help',
    -- '!harpoon',
    -- '!DiffviewFiles',
  },
  buftypes = {
    -- '*',
    -- '!prompt',
    -- '!popup',
  },
  lazy_load = true,
  user_default_options = {
    RGB = true,
    RRGGBB = true,
    RRGGBBAA = true,
    AARRGGBB = false,
    rgb_fn = true,
    hsl_fn = true,
    names = false,
    css = false,
    css_fn = false,
    tailwind = true,
    mode = 'virtualtext',
    virtualtext = '■',
  },
}
