local palette = require("laserwave.palette")

-- =====================
-- = Color definitions =
-- =====================

local highlights = {
  Character  = { fg = palette.color8, },
  ColorColumn = { bg = palette.color4, },
  Comment    = { fg = palette.color47, },
  Conceal    = { fg = palette.color47, bg = palette.color51, },
  Constant   = { fg = palette.color5, },
  Cursor     = { fg = palette.color2, bg = palette.color53, },
  CursorColumn = { bg = palette.color4, },
  CursorLine = { bg = palette.color4, },
  CursorLineNr = { fg = palette.color6, bg = palette.color4,    bold = true },
  DevIconAi  = { fg = palette.color15, },
  DevIconAwk = { fg = palette.color28, },
  DevIconBabelrc = { fg = palette.color15, },
  DevIconBash = { fg = palette.color25, },
  DevIconBashProfile = { fg = palette.color25, },
  DevIconBashrc = { fg = palette.color25, },
  DevIconBat = { fg = palette.color43, },
  DevIconBmp = { fg = palette.color19, },
  DevIconC   = { fg = palette.color63, },
  DevIconCPlusPlus = { fg = palette.color44, },
  DevIconClojure = { fg = palette.color45, },
  DevIconClojureC = { fg = palette.color45, },
  DevIconClojureJS = { fg = palette.color16, },
  DevIconCmakeLists = { fg = palette.color13, },
  DevIconCoffee = { fg = palette.color15, },
  DevIconConf = { fg = palette.color13, },
  DevIconConfigRu = { fg = palette.color37, },
  DevIconCp  = { fg = palette.color16, },
  DevIconCpp = { fg = palette.color16, },
  DevIconCs  = { fg = palette.color21, },
  DevIconCsh = { fg = palette.color28, },
  DevIconCson = { fg = palette.color15, },
  DevIconCss = { fg = palette.color39, },
  DevIconCxx = { fg = palette.color16, },
  DevIconD   = { fg = palette.color70, },
  DevIconDart = { fg = palette.color67, },
  DevIconDb  = { fg = palette.color42, },
  DevIconDefault = { fg = palette.color13, },
  DevIconDiff = { fg = palette.color27, },
  DevIconDoc = { fg = palette.color75, },
  DevIconDockerfile = { fg = palette.color36, },
  DevIconDropbox = { fg = palette.color74, },
  DevIconDsStore = { fg = palette.color27, },
  DevIconDump = { fg = palette.color42, },
  DevIconEdn = { fg = palette.color16, },
  DevIconEex = { fg = palette.color19, },
  DevIconEjs = { fg = palette.color15, },
  DevIconElm = { fg = palette.color16, },
  DevIconErl = { fg = palette.color24, },
  DevIconEx  = { fg = palette.color19, },
  DevIconExs = { fg = palette.color19, },
  DevIconFavicon = { fg = palette.color15, },
  DevIconFish = { fg = palette.color28, },
  DevIconFs  = { fg = palette.color16, },
  DevIconFsharp = { fg = palette.color16, },
  DevIconFsi = { fg = palette.color16, },
  DevIconFsscript = { fg = palette.color16, },
  DevIconFsx = { fg = palette.color16, },
  DevIconGemfile = { fg = palette.color37, },
  DevIconGemspec = { fg = palette.color37, },
  DevIconGif = { fg = palette.color19, },
  DevIconGitAttributes = { fg = palette.color27, },
  DevIconGitCommit = { fg = palette.color27, },
  DevIconGitConfig = { fg = palette.color27, },
  DevIconGitIgnore = { fg = palette.color27, },
  DevIconGitLogo = { fg = palette.color26, },
  DevIconGitlabCI = { fg = palette.color32, },
  DevIconGo  = { fg = palette.color16, },
  DevIconGruntfile = { fg = palette.color18, },
  DevIconGulpfile = { fg = palette.color29, },
  DevIconGvimrc = { fg = palette.color33, },
  DevIconH   = { fg = palette.color19, },
  DevIconHaml = { fg = palette.color62, },
  DevIconHbs = { fg = palette.color22, },
  DevIconHh  = { fg = palette.color19, },
  DevIconHpp = { fg = palette.color19, },
  DevIconHrl = { fg = palette.color24, },
  DevIconHs  = { fg = palette.color19, },
  DevIconHtm = { fg = palette.color60, },
  DevIconHtml = { fg = palette.color60, },
  DevIconHxx = { fg = palette.color19, },
  DevIconIco = { fg = palette.color15, },
  DevIconIni = { fg = palette.color13, },
  DevIconJava = { fg = palette.color29, },
  DevIconJl  = { fg = palette.color30, },
  DevIconJpeg = { fg = palette.color19, },
  DevIconJpg = { fg = palette.color19, },
  DevIconJs  = { fg = palette.color15, },
  DevIconJson = { fg = palette.color15, },
  DevIconJsx = { fg = palette.color16, },
  DevIconKotlin = { fg = palette.color61, },
  DevIconKsh = { fg = palette.color28, },
  DevIconLeex = { fg = palette.color19, },
  DevIconLess = { fg = palette.color39, },
  DevIconLhs = { fg = palette.color19, },
  DevIconLicense = { fg = palette.color35, },
  DevIconLua = { fg = palette.color34, },
  DevIconMakefile = { fg = palette.color13, },
  DevIconMarkdown = { fg = palette.color16, },
  DevIconMd  = { fg = palette.color16, },
  DevIconMdx = { fg = palette.color16, },
  DevIconMixLock = { fg = palette.color19, },
  DevIconMjs = { fg = palette.color56, },
  DevIconMl  = { fg = palette.color18, },
  DevIconMli = { fg = palette.color18, },
  DevIconMustache = { fg = palette.color18, },
  DevIconNPMIgnore = { fg = palette.color64, },
  DevIconNPMLockfile = { fg = palette.color69, },
  DevIconNix = { fg = palette.color41, },
  DevIconNodeModules = { fg = palette.color64, },
  DevIconNunjucks = { fg = palette.color71, },
  DevIconPackageJSON = { fg = palette.color73, },
  DevIconPdf = { fg = palette.color77, },
  DevIconPhp = { fg = palette.color19, },
  DevIconPl  = { fg = palette.color16, },
  DevIconPm  = { fg = palette.color16, },
  DevIconPng = { fg = palette.color19, },
  DevIconPp  = { fg = palette.color46, },
  DevIconPpt = { fg = palette.color17, },
  DevIconProcfile = { fg = palette.color19, },
  DevIconPromptPs1 = { fg = palette.color28, },
  DevIconPsb = { fg = palette.color16, },
  DevIconPsd = { fg = palette.color16, },
  DevIconPy  = { fg = palette.color54, },
  DevIconPyc = { fg = palette.color16, },
  DevIconPyd = { fg = palette.color16, },
  DevIconPyo = { fg = palette.color16, },
  DevIconR   = { fg = palette.color38, },
  DevIconRake = { fg = palette.color37, },
  DevIconRakefile = { fg = palette.color37, },
  DevIconRb  = { fg = palette.color37, },
  DevIconRlib = { fg = palette.color55, },
  DevIconRmd = { fg = palette.color16, },
  DevIconRproj = { fg = palette.color38, },
  DevIconRs  = { fg = palette.color55, },
  DevIconRss = { fg = palette.color57, },
  DevIconSass = { fg = palette.color40, },
  DevIconScala = { fg = palette.color29, },
  DevIconScss = { fg = palette.color40, },
  DevIconSettingsJson = { fg = palette.color20, },
  DevIconSh  = { fg = palette.color28, },
  DevIconSlim = { fg = palette.color60, },
  DevIconSln = { fg = palette.color20, },
  DevIconSql = { fg = palette.color42, },
  DevIconStyl = { fg = palette.color45, },
  DevIconSuo = { fg = palette.color20, },
  DevIconSvg = { fg = palette.color23, },
  DevIconSwift = { fg = palette.color18, },
  DevIconTerminal = { fg = palette.color76, },
  DevIconTex = { fg = palette.color31, },
  DevIconToml = { fg = palette.color13, },
  DevIconTor = { fg = palette.color16, },
  DevIconTs  = { fg = palette.color16, },
  DevIconTsx = { fg = palette.color16, },
  DevIconTwig = { fg = palette.color45, },
  DevIconVagrantfile = { fg = palette.color68, },
  DevIconVim = { fg = palette.color33, },
  DevIconVimrc = { fg = palette.color33, },
  DevIconVue = { fg = palette.color45, },
  DevIconWebmanifest = { fg = palette.color56, },
  DevIconWebp = { fg = palette.color19, },
  DevIconWebpack = { fg = palette.color16, },
  DevIconXcPlayground = { fg = palette.color18, },
  DevIconXls = { fg = palette.color14, },
  DevIconXml = { fg = palette.color18, },
  DevIconXul = { fg = palette.color18, },
  DevIconYaml = { fg = palette.color13, },
  DevIconYarnLockfile = { fg = palette.color66, },
  DevIconYml = { fg = palette.color13, },
  DevIconZsh = { fg = palette.color25, },
  DevIconZshrc = { fg = palette.color25, },
  DiffAdd    = { fg = palette.color5, bg = palette.color4, },
  DiffChange = { fg = palette.color0, bg = palette.color4, },
  DiffDelete = { fg = palette.color3, bg = palette.color4,    bold = true },
  DiffText   = { fg = palette.color0, bg = palette.color47,    bold = true },
  Directory  = { fg = palette.color1, },
  Error      = { fg = palette.color3, bg = palette.color4, },
  ErrorMsg   = { fg = palette.color48, bg = palette.color3, },
  FoldColumn = { fg = palette.color49, bg = palette.color4, },
  Folded     = { fg = palette.color49, bg = palette.color4, },
  Function   = { fg = palette.color52, },
  GitGutterAdd = { fg = palette.color5, },
  GitGutterAddIntraLine = {    reverse = true },
  GitGutterAddInvisible = { fg = palette.color2, bg = palette.color2, },
  GitGutterChange = { fg = palette.color0, },
  GitGutterChangeDelete = { fg = palette.color0, },
  GitGutterChangeInvisible = { fg = palette.color2, bg = palette.color2, },
  GitGutterDelete = { fg = palette.color3, },
  GitGutterDeleteIntraLine = {    reverse = true },
  GitGutterDeleteInvisible = { fg = palette.color2, bg = palette.color2, },
  Identifier = { fg = palette.color0, },
  Ignore     = { fg = palette.color2, },
  IncSearch  = { fg = palette.color5, bg = palette.color4,    reverse = true },
  LightlineLeft_command_0 = { fg = palette.color10, bg = palette.color72, },
  LightlineLeft_command_0_1 = { fg = palette.color72, bg = palette.color11, },
  LightlineLeft_command_0_tabsel = { fg = palette.color72, bg = palette.color9, },
  LightlineLeft_command_1 = { fg = palette.color10, bg = palette.color11, },
  LightlineLeft_command_1_2 = { fg = palette.color11, bg = palette.color12, },
  LightlineLeft_command_1_tabsel = { fg = palette.color11, bg = palette.color9, },
  LightlineLeft_command_2 = { fg = palette.color2, bg = palette.color12, },
  LightlineLeft_command_2_3 = { fg = palette.color12, bg = palette.color0, },
  LightlineLeft_command_2_tabsel = { fg = palette.color12, bg = palette.color9, },
  LightlineLeft_command_tabsel = { fg = palette.color2, bg = palette.color9, },
  LightlineLeft_command_tabsel_0 = { fg = palette.color9, bg = palette.color72, },
  LightlineLeft_command_tabsel_1 = { fg = palette.color9, bg = palette.color11, },
  LightlineLeft_command_tabsel_2 = { fg = palette.color9, bg = palette.color12, },
  LightlineLeft_command_tabsel_3 = { fg = palette.color9, bg = palette.color0, },
  LightlineLeft_command_tabsel_tabsel = { fg = palette.color9, bg = palette.color9, },
  LightlineLeft_inactive_0 = { fg = palette.color49, bg = palette.color4, },
  LightlineLeft_inactive_0_1 = { fg = palette.color4, bg = palette.color4, },
  LightlineLeft_inactive_0_tabsel = { fg = palette.color4, bg = palette.color9, },
  LightlineLeft_inactive_tabsel = { fg = palette.color2, bg = palette.color9, },
  LightlineLeft_inactive_tabsel_0 = { fg = palette.color9, bg = palette.color4, },
  LightlineLeft_inactive_tabsel_1 = { fg = palette.color9, bg = palette.color4, },
  LightlineLeft_inactive_tabsel_tabsel = { fg = palette.color9, bg = palette.color9, },
  LightlineLeft_insert_0 = { fg = palette.color2, bg = palette.color1, },
  LightlineLeft_insert_0_1 = { fg = palette.color1, bg = palette.color9, },
  LightlineLeft_insert_0_tabsel = { fg = palette.color1, bg = palette.color9, },
  LightlineLeft_insert_1 = { fg = palette.color2, bg = palette.color9, },
  LightlineLeft_insert_1_2 = { fg = palette.color9, bg = palette.color0, },
  LightlineLeft_insert_1_tabsel = { fg = palette.color9, bg = palette.color9, },
  LightlineLeft_insert_2 = { fg = palette.color2, bg = palette.color0, },
  LightlineLeft_insert_2_3 = { fg = palette.color0, bg = palette.color0, },
  LightlineLeft_insert_2_tabsel = { fg = palette.color0, bg = palette.color9, },
  LightlineLeft_insert_tabsel = { fg = palette.color2, bg = palette.color9, },
  LightlineLeft_insert_tabsel_0 = { fg = palette.color9, bg = palette.color1, },
  LightlineLeft_insert_tabsel_1 = { fg = palette.color9, bg = palette.color9, },
  LightlineLeft_insert_tabsel_2 = { fg = palette.color9, bg = palette.color0, },
  LightlineLeft_insert_tabsel_3 = { fg = palette.color9, bg = palette.color0, },
  LightlineLeft_insert_tabsel_tabsel = { fg = palette.color9, bg = palette.color9, },
  LightlineLeft_normal_0 = { fg = palette.color10, bg = palette.color72, },
  LightlineLeft_normal_0_1 = { fg = palette.color72, bg = palette.color11, },
  LightlineLeft_normal_0_tabsel = { fg = palette.color72, bg = palette.color9, },
  LightlineLeft_normal_1 = { fg = palette.color10, bg = palette.color11, },
  LightlineLeft_normal_1_2 = { fg = palette.color11, bg = palette.color12, },
  LightlineLeft_normal_1_tabsel = { fg = palette.color11, bg = palette.color9, },
  LightlineLeft_normal_2 = { fg = palette.color2, bg = palette.color12, },
  LightlineLeft_normal_2_3 = { fg = palette.color12, bg = palette.color0, },
  LightlineLeft_normal_2_tabsel = { fg = palette.color12, bg = palette.color9, },
  LightlineLeft_normal_tabsel = { fg = palette.color2, bg = palette.color9, },
  LightlineLeft_normal_tabsel_0 = { fg = palette.color9, bg = palette.color72, },
  LightlineLeft_normal_tabsel_1 = { fg = palette.color9, bg = palette.color11, },
  LightlineLeft_normal_tabsel_2 = { fg = palette.color9, bg = palette.color12, },
  LightlineLeft_normal_tabsel_3 = { fg = palette.color9, bg = palette.color0, },
  LightlineLeft_normal_tabsel_tabsel = { fg = palette.color9, bg = palette.color9, },
  LightlineLeft_replace_0 = { fg = palette.color2, bg = palette.color52, },
  LightlineLeft_replace_0_1 = { fg = palette.color52, bg = palette.color9, },
  LightlineLeft_replace_0_tabsel = { fg = palette.color52, bg = palette.color9, },
  LightlineLeft_replace_1 = { fg = palette.color2, bg = palette.color9, },
  LightlineLeft_replace_1_2 = { fg = palette.color9, bg = palette.color0, },
  LightlineLeft_replace_1_tabsel = { fg = palette.color9, bg = palette.color9, },
  LightlineLeft_replace_2 = { fg = palette.color2, bg = palette.color0, },
  LightlineLeft_replace_2_3 = { fg = palette.color0, bg = palette.color0, },
  LightlineLeft_replace_2_tabsel = { fg = palette.color0, bg = palette.color9, },
  LightlineLeft_replace_tabsel = { fg = palette.color2, bg = palette.color9, },
  LightlineLeft_replace_tabsel_0 = { fg = palette.color9, bg = palette.color52, },
  LightlineLeft_replace_tabsel_1 = { fg = palette.color9, bg = palette.color9, },
  LightlineLeft_replace_tabsel_2 = { fg = palette.color9, bg = palette.color0, },
  LightlineLeft_replace_tabsel_3 = { fg = palette.color9, bg = palette.color0, },
  LightlineLeft_replace_tabsel_tabsel = { fg = palette.color9, bg = palette.color9, },
  LightlineLeft_select_0 = { fg = palette.color10, bg = palette.color3, },
  LightlineLeft_select_0_1 = { fg = palette.color3, bg = palette.color9, },
  LightlineLeft_select_0_tabsel = { fg = palette.color3, bg = palette.color9, },
  LightlineLeft_select_1 = { fg = palette.color2, bg = palette.color9, },
  LightlineLeft_select_1_2 = { fg = palette.color9, bg = palette.color0, },
  LightlineLeft_select_1_tabsel = { fg = palette.color9, bg = palette.color9, },
  LightlineLeft_select_2 = { fg = palette.color2, bg = palette.color0, },
  LightlineLeft_select_2_3 = { fg = palette.color0, bg = palette.color0, },
  LightlineLeft_select_2_tabsel = { fg = palette.color0, bg = palette.color9, },
  LightlineLeft_select_tabsel = { fg = palette.color2, bg = palette.color9, },
  LightlineLeft_select_tabsel_0 = { fg = palette.color9, bg = palette.color3, },
  LightlineLeft_select_tabsel_1 = { fg = palette.color9, bg = palette.color9, },
  LightlineLeft_select_tabsel_2 = { fg = palette.color9, bg = palette.color0, },
  LightlineLeft_select_tabsel_3 = { fg = palette.color9, bg = palette.color0, },
  LightlineLeft_select_tabsel_tabsel = { fg = palette.color9, bg = palette.color9, },
  LightlineLeft_tabline_0 = { fg = palette.color2, bg = palette.color0, },
  LightlineLeft_tabline_0_1 = { fg = palette.color0, bg = palette.color0, },
  LightlineLeft_tabline_0_tabsel = { fg = palette.color0, bg = palette.color9, },
  LightlineLeft_tabline_tabsel = { fg = palette.color2, bg = palette.color9, },
  LightlineLeft_tabline_tabsel_0 = { fg = palette.color9, bg = palette.color0, },
  LightlineLeft_tabline_tabsel_1 = { fg = palette.color9, bg = palette.color0, },
  LightlineLeft_tabline_tabsel_tabsel = { fg = palette.color9, bg = palette.color9, },
  LightlineLeft_terminal_0 = { fg = palette.color2, bg = palette.color1, },
  LightlineLeft_terminal_0_1 = { fg = palette.color1, bg = palette.color9, },
  LightlineLeft_terminal_0_tabsel = { fg = palette.color1, bg = palette.color9, },
  LightlineLeft_terminal_1 = { fg = palette.color2, bg = palette.color9, },
  LightlineLeft_terminal_1_2 = { fg = palette.color9, bg = palette.color0, },
  LightlineLeft_terminal_1_tabsel = { fg = palette.color9, bg = palette.color9, },
  LightlineLeft_terminal_2 = { fg = palette.color2, bg = palette.color0, },
  LightlineLeft_terminal_2_3 = { fg = palette.color0, bg = palette.color0, },
  LightlineLeft_terminal_2_tabsel = { fg = palette.color0, bg = palette.color9, },
  LightlineLeft_terminal_tabsel = { fg = palette.color2, bg = palette.color9, },
  LightlineLeft_terminal_tabsel_0 = { fg = palette.color9, bg = palette.color1, },
  LightlineLeft_terminal_tabsel_1 = { fg = palette.color9, bg = palette.color9, },
  LightlineLeft_terminal_tabsel_2 = { fg = palette.color9, bg = palette.color0, },
  LightlineLeft_terminal_tabsel_3 = { fg = palette.color9, bg = palette.color0, },
  LightlineLeft_terminal_tabsel_tabsel = { fg = palette.color9, bg = palette.color9, },
  LightlineLeft_visual_0 = { fg = palette.color10, bg = palette.color3, },
  LightlineLeft_visual_0_1 = { fg = palette.color3, bg = palette.color9, },
  LightlineLeft_visual_0_tabsel = { fg = palette.color3, bg = palette.color9, },
  LightlineLeft_visual_1 = { fg = palette.color2, bg = palette.color9, },
  LightlineLeft_visual_1_2 = { fg = palette.color9, bg = palette.color0, },
  LightlineLeft_visual_1_tabsel = { fg = palette.color9, bg = palette.color9, },
  LightlineLeft_visual_2 = { fg = palette.color2, bg = palette.color0, },
  LightlineLeft_visual_2_3 = { fg = palette.color0, bg = palette.color0, },
  LightlineLeft_visual_2_tabsel = { fg = palette.color0, bg = palette.color9, },
  LightlineLeft_visual_tabsel = { fg = palette.color2, bg = palette.color9, },
  LightlineLeft_visual_tabsel_0 = { fg = palette.color9, bg = palette.color3, },
  LightlineLeft_visual_tabsel_1 = { fg = palette.color9, bg = palette.color9, },
  LightlineLeft_visual_tabsel_2 = { fg = palette.color9, bg = palette.color0, },
  LightlineLeft_visual_tabsel_3 = { fg = palette.color9, bg = palette.color0, },
  LightlineLeft_visual_tabsel_tabsel = { fg = palette.color9, bg = palette.color9, },
  LightlineMiddle_command = { fg = palette.color2, bg = palette.color0, },
  LightlineMiddle_inactive = { fg = palette.color2, bg = palette.color4, },
  LightlineMiddle_insert = { fg = palette.color2, bg = palette.color0, },
  LightlineMiddle_normal = { fg = palette.color2, bg = palette.color0, },
  LightlineMiddle_replace = { fg = palette.color2, bg = palette.color0, },
  LightlineMiddle_select = { fg = palette.color2, bg = palette.color0, },
  LightlineMiddle_tabline = { fg = palette.color2, bg = palette.color0, },
  LightlineMiddle_terminal = { fg = palette.color2, bg = palette.color0, },
  LightlineMiddle_visual = { fg = palette.color2, bg = palette.color0, },
  LightlineRight_command_0 = { fg = palette.color10, bg = palette.color11, },
  LightlineRight_command_0_1 = { fg = palette.color11, bg = palette.color12, },
  LightlineRight_command_0_tabsel = { fg = palette.color11, bg = palette.color9, },
  LightlineRight_command_1 = { fg = palette.color2, bg = palette.color12, },
  LightlineRight_command_1_2 = { fg = palette.color12, bg = palette.color0, },
  LightlineRight_command_1_tabsel = { fg = palette.color12, bg = palette.color9, },
  LightlineRight_command_tabsel = { fg = palette.color2, bg = palette.color9, },
  LightlineRight_command_tabsel_0 = { fg = palette.color9, bg = palette.color11, },
  LightlineRight_command_tabsel_1 = { fg = palette.color9, bg = palette.color12, },
  LightlineRight_command_tabsel_2 = { fg = palette.color9, bg = palette.color0, },
  LightlineRight_command_tabsel_tabsel = { fg = palette.color9, bg = palette.color9, },
  LightlineRight_inactive_0 = { fg = palette.color4, bg = palette.color6, },
  LightlineRight_inactive_0_1 = { fg = palette.color6, bg = palette.color4, },
  LightlineRight_inactive_0_tabsel = { fg = palette.color6, bg = palette.color9, },
  LightlineRight_inactive_1 = { fg = palette.color6, bg = palette.color4, },
  LightlineRight_inactive_1_2 = { fg = palette.color4, bg = palette.color4, },
  LightlineRight_inactive_1_tabsel = { fg = palette.color4, bg = palette.color9, },
  LightlineRight_inactive_tabsel = { fg = palette.color2, bg = palette.color9, },
  LightlineRight_inactive_tabsel_0 = { fg = palette.color9, bg = palette.color6, },
  LightlineRight_inactive_tabsel_1 = { fg = palette.color9, bg = palette.color4, },
  LightlineRight_inactive_tabsel_2 = { fg = palette.color9, bg = palette.color4, },
  LightlineRight_inactive_tabsel_tabsel = { fg = palette.color9, bg = palette.color9, },
  LightlineRight_insert_0 = { fg = palette.color10, bg = palette.color11, },
  LightlineRight_insert_0_1 = { fg = palette.color11, bg = palette.color12, },
  LightlineRight_insert_0_tabsel = { fg = palette.color11, bg = palette.color9, },
  LightlineRight_insert_1 = { fg = palette.color2, bg = palette.color12, },
  LightlineRight_insert_1_2 = { fg = palette.color12, bg = palette.color0, },
  LightlineRight_insert_1_tabsel = { fg = palette.color12, bg = palette.color9, },
  LightlineRight_insert_tabsel = { fg = palette.color2, bg = palette.color9, },
  LightlineRight_insert_tabsel_0 = { fg = palette.color9, bg = palette.color11, },
  LightlineRight_insert_tabsel_1 = { fg = palette.color9, bg = palette.color12, },
  LightlineRight_insert_tabsel_2 = { fg = palette.color9, bg = palette.color0, },
  LightlineRight_insert_tabsel_tabsel = { fg = palette.color9, bg = palette.color9, },
  LightlineRight_normal_0 = { fg = palette.color10, bg = palette.color11, },
  LightlineRight_normal_0_1 = { fg = palette.color11, bg = palette.color12, },
  LightlineRight_normal_0_tabsel = { fg = palette.color11, bg = palette.color9, },
  LightlineRight_normal_1 = { fg = palette.color2, bg = palette.color12, },
  LightlineRight_normal_1_2 = { fg = palette.color12, bg = palette.color0, },
  LightlineRight_normal_1_tabsel = { fg = palette.color12, bg = palette.color9, },
  LightlineRight_normal_tabsel = { fg = palette.color2, bg = palette.color9, },
  LightlineRight_normal_tabsel_0 = { fg = palette.color9, bg = palette.color11, },
  LightlineRight_normal_tabsel_1 = { fg = palette.color9, bg = palette.color12, },
  LightlineRight_normal_tabsel_2 = { fg = palette.color9, bg = palette.color0, },
  LightlineRight_normal_tabsel_tabsel = { fg = palette.color9, bg = palette.color9, },
  LightlineRight_replace_0 = { fg = palette.color10, bg = palette.color11, },
  LightlineRight_replace_0_1 = { fg = palette.color11, bg = palette.color12, },
  LightlineRight_replace_0_tabsel = { fg = palette.color11, bg = palette.color9, },
  LightlineRight_replace_1 = { fg = palette.color2, bg = palette.color12, },
  LightlineRight_replace_1_2 = { fg = palette.color12, bg = palette.color0, },
  LightlineRight_replace_1_tabsel = { fg = palette.color12, bg = palette.color9, },
  LightlineRight_replace_tabsel = { fg = palette.color2, bg = palette.color9, },
  LightlineRight_replace_tabsel_0 = { fg = palette.color9, bg = palette.color11, },
  LightlineRight_replace_tabsel_1 = { fg = palette.color9, bg = palette.color12, },
  LightlineRight_replace_tabsel_2 = { fg = palette.color9, bg = palette.color0, },
  LightlineRight_replace_tabsel_tabsel = { fg = palette.color9, bg = palette.color9, },
  LightlineRight_select_0 = { fg = palette.color10, bg = palette.color11, },
  LightlineRight_select_0_1 = { fg = palette.color11, bg = palette.color12, },
  LightlineRight_select_0_tabsel = { fg = palette.color11, bg = palette.color9, },
  LightlineRight_select_1 = { fg = palette.color2, bg = palette.color12, },
  LightlineRight_select_1_2 = { fg = palette.color12, bg = palette.color0, },
  LightlineRight_select_1_tabsel = { fg = palette.color12, bg = palette.color9, },
  LightlineRight_select_tabsel = { fg = palette.color2, bg = palette.color9, },
  LightlineRight_select_tabsel_0 = { fg = palette.color9, bg = palette.color11, },
  LightlineRight_select_tabsel_1 = { fg = palette.color9, bg = palette.color12, },
  LightlineRight_select_tabsel_2 = { fg = palette.color9, bg = palette.color0, },
  LightlineRight_select_tabsel_tabsel = { fg = palette.color9, bg = palette.color9, },
  LightlineRight_tabline_0 = { fg = palette.color2, bg = palette.color0, },
  LightlineRight_tabline_tabsel = { fg = palette.color2, bg = palette.color9, },
  LightlineRight_tabline_tabsel_0 = { fg = palette.color9, bg = palette.color0, },
  LightlineRight_tabline_tabsel_tabsel = { fg = palette.color9, bg = palette.color9, },
  LightlineRight_terminal_0 = { fg = palette.color10, bg = palette.color11, },
  LightlineRight_terminal_0_1 = { fg = palette.color11, bg = palette.color12, },
  LightlineRight_terminal_0_tabsel = { fg = palette.color11, bg = palette.color9, },
  LightlineRight_terminal_1 = { fg = palette.color2, bg = palette.color12, },
  LightlineRight_terminal_1_2 = { fg = palette.color12, bg = palette.color0, },
  LightlineRight_terminal_1_tabsel = { fg = palette.color12, bg = palette.color9, },
  LightlineRight_terminal_tabsel = { fg = palette.color2, bg = palette.color9, },
  LightlineRight_terminal_tabsel_0 = { fg = palette.color9, bg = palette.color11, },
  LightlineRight_terminal_tabsel_1 = { fg = palette.color9, bg = palette.color12, },
  LightlineRight_terminal_tabsel_2 = { fg = palette.color9, bg = palette.color0, },
  LightlineRight_terminal_tabsel_tabsel = { fg = palette.color9, bg = palette.color9, },
  LightlineRight_visual_0 = { fg = palette.color10, bg = palette.color11, },
  LightlineRight_visual_0_1 = { fg = palette.color11, bg = palette.color12, },
  LightlineRight_visual_0_tabsel = { fg = palette.color11, bg = palette.color9, },
  LightlineRight_visual_1 = { fg = palette.color2, bg = palette.color12, },
  LightlineRight_visual_1_2 = { fg = palette.color12, bg = palette.color0, },
  LightlineRight_visual_1_tabsel = { fg = palette.color12, bg = palette.color9, },
  LightlineRight_visual_tabsel = { fg = palette.color2, bg = palette.color9, },
  LightlineRight_visual_tabsel_0 = { fg = palette.color9, bg = palette.color11, },
  LightlineRight_visual_tabsel_1 = { fg = palette.color9, bg = palette.color12, },
  LightlineRight_visual_tabsel_2 = { fg = palette.color9, bg = palette.color0, },
  LightlineRight_visual_tabsel_tabsel = { fg = palette.color9, bg = palette.color9, },
  LineNr     = { fg = palette.color47, bg = palette.color2, },
  MatchParen = { bg = palette.color47, },
  ModeMsg    = {    bold = true },
  MoreMsg    = { fg = palette.color2, bg = palette.color8,    bold = true },
  NERDTreeCWD = { fg = palette.color3, },
  NERDTreeDirSlash = { fg = palette.color1, },
  NERDTreeExecFile = { fg = palette.color8, },
  NonText    = { fg = palette.color47, bg = palette.color2,    bold = true },
  Normal     = { fg = palette.color53, bg = palette.color2, },
  NvimInternalError = { fg = palette.color81, bg = palette.color81, },
  NvimTreeExecFile = { fg = palette.color8,    bold = true },
  NvimTreeFolderIcon = { fg = palette.color58, },
  NvimTreeGitDeleted = { fg = palette.color59, },
  NvimTreeGitDirty = { fg = palette.color59, },
  NvimTreeGitMerge = { fg = palette.color78, },
  NvimTreeGitNew = { fg = palette.color72, },
  NvimTreeGitRenamed = { fg = palette.color65, },
  NvimTreeGitStaged = { fg = palette.color8, },
  NvimTreeImageFile = { fg = palette.color65,    bold = true },
  NvimTreeIndentMarker = { fg = palette.color58, },
  NvimTreeRootFolder = { fg = palette.color65, },
  NvimTreeSpecialFile = { fg = palette.color72,    bold = true,   underline = true },
  NvimTreeSymlink = { fg = palette.color50,    bold = true },
  Pmenu      = { fg = palette.color53, bg = palette.color4, },
  PmenuSbar  = { fg = palette.color5, bg = palette.color4, },
  PmenuSel   = { fg = palette.color8, bg = palette.color4, },
  PmenuThumb = { fg = palette.color3, bg = palette.color47, },
  PreProc    = { fg = palette.color72, },
  Question   = { fg = palette.color48, bg = palette.color4,    bold = true },
  RedrawDebugClear = { bg = palette.color79, },
  RedrawDebugComposed = { bg = palette.color80, },
  RedrawDebugNormal = {    reverse = true },
  RedrawDebugRecompose = { bg = palette.color81, },
  Search     = { fg = palette.color5, bg = palette.color4, },
  SignColumn = { fg = palette.color50, bg = palette.color2, },
  Special    = { fg = palette.color8, },
  SpecialKey = { fg = palette.color3, bg = palette.color2, },
  SpellBad   = { fg = palette.color3,    undercurl = true },
  SpellCap   = { fg = palette.color0,    undercurl = true },
  SpellLocal = { fg = palette.color8,    undercurl = true },
  SpellRare  = { fg = palette.color52,    undercurl = true },
  Statement  = { fg = palette.color1,    bold = true },
  StatusLine = { fg = palette.color49, bg = palette.color4, },
  StatusLineNC = {    reverse = true },
  TabLine    = { fg = palette.color7, bg = palette.color4,    underline = true },
  TabLineFill = { bg = palette.color4,    reverse = true },
  TabLineSel = { fg = palette.color53, bg = palette.color2,    bold = true },
  TermCursor = {    reverse = true },
  Title      = { fg = palette.color1,    bold = true },
  Todo       = { fg = palette.color3, bg = palette.color4, },
  Type       = { fg = palette.color3,    bold = true },
  Underlined = { fg = palette.color1,    underline = true },
  VertSplit  = { fg = palette.color2, bg = palette.color6,    reverse = true },
  Visual     = { bg = palette.color4, },
  VisualNOS  = { fg = palette.color3, bg = palette.color4, },
  WarningMsg = { fg = palette.color3, },
  WildMenu   = { fg = palette.color8, bg = palette.color4, },
  gitcommitComment = { fg = palette.color6, },
  gitcommitDiscardedFile = { fg = palette.color0, },
  gitcommitDiscardedType = { fg = palette.color0, },
  gitcommitHead = { fg = palette.color6, },
  gitcommitHeader = { fg = palette.color7, },
  gitcommitOnBranch = { fg = palette.color6, },
  gitcommitSelectedFile = { fg = palette.color5, },
  gitcommitSelectedType = { fg = palette.color5, },
  gitcommitUntrackedFile = { fg = palette.color3, },
  lCursor    = { fg = palette.color2, bg = palette.color53, },
  Boolean    = {link = 'Constant'},
  CompeDocumentation = {link = 'NormalFloat'},
  Conditional = {link = 'Statement'},
  Debug      = {link = 'Special'},
  Define     = {link = 'PreProc'},
  Delimiter  = {link = 'Special'},
  EndOfBuffer = {link = 'NonText'},
  Exception  = {link = 'Statement'},
  Float      = {link = 'Number'},
  FloatBorder = {link = 'VertSplit'},
  GitGutterAddLine = {link = 'DiffAdd'},
  GitGutterAddLineNr = {link = 'CursorLineNr'},
  GitGutterChangeDeleteInvisible = {link = 'GitGutterChangeInvisible'},
  GitGutterChangeDeleteLine = {link = 'GitGutterChangeLine'},
  GitGutterChangeDeleteLineNr = {link = 'CursorLineNr'},
  GitGutterChangeLine = {link = 'DiffChange'},
  GitGutterChangeLineNr = {link = 'CursorLineNr'},
  GitGutterDeleteLine = {link = 'DiffDelete'},
  GitGutterDeleteLineNr = {link = 'CursorLineNr'},
  Include    = {link = 'PreProc'},
  Keyword    = {link = 'Statement'},
  Label      = {link = 'Statement'},
  LspDiagnosticsFloatingError = {link = 'LspDiagnosticsDefaultError'},
  LspDiagnosticsFloatingHint = {link = 'LspDiagnosticsDefaultHint'},
  LspDiagnosticsFloatingInformation = {link = 'LspDiagnosticsDefaultInformation'},
  LspDiagnosticsFloatingWarning = {link = 'LspDiagnosticsDefaultWarning'},
  LspDiagnosticsSignError = {link = 'LspDiagnosticsDefaultError'},
  LspDiagnosticsSignHint = {link = 'LspDiagnosticsDefaultHint'},
  LspDiagnosticsSignInformation = {link = 'LspDiagnosticsDefaultInformation'},
  LspDiagnosticsSignWarning = {link = 'LspDiagnosticsDefaultWarning'},
  LspDiagnosticsVirtualTextError = {link = 'LspDiagnosticsDefaultError'},
  LspDiagnosticsVirtualTextHint = {link = 'LspDiagnosticsDefaultHint'},
  LspDiagnosticsVirtualTextInformation = {link = 'LspDiagnosticsDefaultInformation'},
  LspDiagnosticsVirtualTextWarning = {link = 'LspDiagnosticsDefaultWarning'},
  Macro      = {link = 'PreProc'},
  MsgSeparator = {link = 'StatusLine'},
  NormalFloat = {link = 'Pmenu'},
  Number     = {link = 'Constant'},
  NvimAnd    = {link = 'NvimBinaryOperator'},
  NvimArrow  = {link = 'Delimiter'},
  NvimAssignment = {link = 'Operator'},
  NvimAssignmentWithAddition = {link = 'NvimAugmentedAssignment'},
  NvimAssignmentWithConcatenation = {link = 'NvimAugmentedAssignment'},
  NvimAssignmentWithSubtraction = {link = 'NvimAugmentedAssignment'},
  NvimAugmentedAssignment = {link = 'NvimAssignment'},
  NvimBinaryMinus = {link = 'NvimBinaryOperator'},
  NvimBinaryOperator = {link = 'NvimOperator'},
  NvimBinaryPlus = {link = 'NvimBinaryOperator'},
  NvimCallingParenthesis = {link = 'NvimParenthesis'},
  NvimColon  = {link = 'Delimiter'},
  NvimComma  = {link = 'Delimiter'},
  NvimComparison = {link = 'NvimBinaryOperator'},
  NvimComparisonModifier = {link = 'NvimComparison'},
  NvimConcat = {link = 'NvimBinaryOperator'},
  NvimConcatOrSubscript = {link = 'NvimConcat'},
  NvimContainer = {link = 'NvimParenthesis'},
  NvimCurly  = {link = 'NvimSubscript'},
  NvimDict   = {link = 'NvimContainer'},
  NvimDivision = {link = 'NvimBinaryOperator'},
  NvimDoubleQuote = {link = 'NvimStringQuote'},
  NvimDoubleQuotedBody = {link = 'NvimStringBody'},
  NvimDoubleQuotedEscape = {link = 'NvimStringSpecial'},
  NvimDoubleQuotedUnknownEscape = {link = 'NvimInvalidValue'},
  NvimEnvironmentName = {link = 'NvimIdentifier'},
  NvimEnvironmentSigil = {link = 'NvimOptionSigil'},
  NvimFigureBrace = {link = 'NvimInternalError'},
  NvimFloat  = {link = 'NvimNumber'},
  NvimIdentifier = {link = 'Identifier'},
  NvimIdentifierKey = {link = 'NvimIdentifier'},
  NvimIdentifierName = {link = 'NvimIdentifier'},
  NvimIdentifierScope = {link = 'NvimIdentifier'},
  NvimIdentifierScopeDelimiter = {link = 'NvimIdentifier'},
  NvimInvalid = {link = 'Error'},
  NvimInvalidAnd = {link = 'NvimInvalidBinaryOperator'},
  NvimInvalidArrow = {link = 'NvimInvalidDelimiter'},
  NvimInvalidAssignment = {link = 'NvimInvalid'},
  NvimInvalidAssignmentWithAddition = {link = 'NvimInvalidAugmentedAssignment'},
  NvimInvalidAssignmentWithConcatenation = {link = 'NvimInvalidAugmentedAssignment'},
  NvimInvalidAssignmentWithSubtraction = {link = 'NvimInvalidAugmentedAssignment'},
  NvimInvalidAugmentedAssignment = {link = 'NvimInvalidAssignment'},
  NvimInvalidBinaryMinus = {link = 'NvimInvalidBinaryOperator'},
  NvimInvalidBinaryOperator = {link = 'NvimInvalidOperator'},
  NvimInvalidBinaryPlus = {link = 'NvimInvalidBinaryOperator'},
  NvimInvalidCallingParenthesis = {link = 'NvimInvalidParenthesis'},
  NvimInvalidColon = {link = 'NvimInvalidDelimiter'},
  NvimInvalidComma = {link = 'NvimInvalidDelimiter'},
  NvimInvalidComparison = {link = 'NvimInvalidBinaryOperator'},
  NvimInvalidComparisonModifier = {link = 'NvimInvalidComparison'},
  NvimInvalidConcat = {link = 'NvimInvalidBinaryOperator'},
  NvimInvalidConcatOrSubscript = {link = 'NvimInvalidConcat'},
  NvimInvalidContainer = {link = 'NvimInvalidParenthesis'},
  NvimInvalidCurly = {link = 'NvimInvalidSubscript'},
  NvimInvalidDelimiter = {link = 'NvimInvalid'},
  NvimInvalidDict = {link = 'NvimInvalidContainer'},
  NvimInvalidDivision = {link = 'NvimInvalidBinaryOperator'},
  NvimInvalidDoubleQuote = {link = 'NvimInvalidStringQuote'},
  NvimInvalidDoubleQuotedBody = {link = 'NvimInvalidStringBody'},
  NvimInvalidDoubleQuotedEscape = {link = 'NvimInvalidStringSpecial'},
  NvimInvalidDoubleQuotedUnknownEscape = {link = 'NvimInvalidValue'},
  NvimInvalidEnvironmentName = {link = 'NvimInvalidIdentifier'},
  NvimInvalidEnvironmentSigil = {link = 'NvimInvalidOptionSigil'},
  NvimInvalidFigureBrace = {link = 'NvimInvalidDelimiter'},
  NvimInvalidFloat = {link = 'NvimInvalidNumber'},
  NvimInvalidIdentifier = {link = 'NvimInvalidValue'},
  NvimInvalidIdentifierKey = {link = 'NvimInvalidIdentifier'},
  NvimInvalidIdentifierName = {link = 'NvimInvalidIdentifier'},
  NvimInvalidIdentifierScope = {link = 'NvimInvalidIdentifier'},
  NvimInvalidIdentifierScopeDelimiter = {link = 'NvimInvalidIdentifier'},
  NvimInvalidLambda = {link = 'NvimInvalidParenthesis'},
  NvimInvalidList = {link = 'NvimInvalidContainer'},
  NvimInvalidMod = {link = 'NvimInvalidBinaryOperator'},
  NvimInvalidMultiplication = {link = 'NvimInvalidBinaryOperator'},
  NvimInvalidNestingParenthesis = {link = 'NvimInvalidParenthesis'},
  NvimInvalidNot = {link = 'NvimInvalidUnaryOperator'},
  NvimInvalidNumber = {link = 'NvimInvalidValue'},
  NvimInvalidNumberPrefix = {link = 'NvimInvalidNumber'},
  NvimInvalidOperator = {link = 'NvimInvalid'},
  NvimInvalidOptionName = {link = 'NvimInvalidIdentifier'},
  NvimInvalidOptionScope = {link = 'NvimInvalidIdentifierScope'},
  NvimInvalidOptionScopeDelimiter = {link = 'NvimInvalidIdentifierScopeDelimiter'},
  NvimInvalidOptionSigil = {link = 'NvimInvalidIdentifier'},
  NvimInvalidOr = {link = 'NvimInvalidBinaryOperator'},
  NvimInvalidParenthesis = {link = 'NvimInvalidDelimiter'},
  NvimInvalidPlainAssignment = {link = 'NvimInvalidAssignment'},
  NvimInvalidRegister = {link = 'NvimInvalidValue'},
  NvimInvalidSingleQuote = {link = 'NvimInvalidStringQuote'},
  NvimInvalidSingleQuotedBody = {link = 'NvimInvalidStringBody'},
  NvimInvalidSingleQuotedQuote = {link = 'NvimInvalidStringSpecial'},
  NvimInvalidSingleQuotedUnknownEscape = {link = 'NvimInternalError'},
  NvimInvalidSpacing = {link = 'ErrorMsg'},
  NvimInvalidString = {link = 'NvimInvalidValue'},
  NvimInvalidStringBody = {link = 'NvimStringBody'},
  NvimInvalidStringQuote = {link = 'NvimInvalidString'},
  NvimInvalidStringSpecial = {link = 'NvimStringSpecial'},
  NvimInvalidSubscript = {link = 'NvimInvalidParenthesis'},
  NvimInvalidSubscriptBracket = {link = 'NvimInvalidSubscript'},
  NvimInvalidSubscriptColon = {link = 'NvimInvalidSubscript'},
  NvimInvalidTernary = {link = 'NvimInvalidOperator'},
  NvimInvalidTernaryColon = {link = 'NvimInvalidTernary'},
  NvimInvalidUnaryMinus = {link = 'NvimInvalidUnaryOperator'},
  NvimInvalidUnaryOperator = {link = 'NvimInvalidOperator'},
  NvimInvalidUnaryPlus = {link = 'NvimInvalidUnaryOperator'},
  NvimInvalidValue = {link = 'NvimInvalid'},
  NvimLambda = {link = 'NvimParenthesis'},
  NvimList   = {link = 'NvimContainer'},
  NvimMod    = {link = 'NvimBinaryOperator'},
  NvimMultiplication = {link = 'NvimBinaryOperator'},
  NvimNestingParenthesis = {link = 'NvimParenthesis'},
  NvimNot    = {link = 'NvimUnaryOperator'},
  NvimNumber = {link = 'Number'},
  NvimNumberPrefix = {link = 'Type'},
  NvimOperator = {link = 'Operator'},
  NvimOptionName = {link = 'NvimIdentifier'},
  NvimOptionScope = {link = 'NvimIdentifierScope'},
  NvimOptionScopeDelimiter = {link = 'NvimIdentifierScopeDelimiter'},
  NvimOptionSigil = {link = 'Type'},
  NvimOr     = {link = 'NvimBinaryOperator'},
  NvimParenthesis = {link = 'Delimiter'},
  NvimPlainAssignment = {link = 'NvimAssignment'},
  NvimRegister = {link = 'SpecialChar'},
  NvimSingleQuote = {link = 'NvimStringQuote'},
  NvimSingleQuotedBody = {link = 'NvimStringBody'},
  NvimSingleQuotedQuote = {link = 'NvimStringSpecial'},
  NvimSingleQuotedUnknownEscape = {link = 'NvimInternalError'},
  NvimSpacing = {link = 'Normal'},
  NvimString = {link = 'String'},
  NvimStringBody = {link = 'NvimString'},
  NvimStringQuote = {link = 'NvimString'},
  NvimStringSpecial = {link = 'SpecialChar'},
  NvimSubscript = {link = 'NvimParenthesis'},
  NvimSubscriptBracket = {link = 'NvimSubscript'},
  NvimSubscriptColon = {link = 'NvimSubscript'},
  NvimTernary = {link = 'NvimOperator'},
  NvimTernaryColon = {link = 'NvimTernary'},
  NvimTreeCursorColumn = {link = 'CursorColumn'},
  NvimTreeCursorLine = {link = 'CursorLine'},
  NvimTreeEmptyFolderName = {link = 'Directory'},
  NvimTreeEndOfBuffer = {link = 'EndOfBuffer'},
  NvimTreeFileDeleted = {link = 'NvimTreeGitDeleted'},
  NvimTreeFileDirty = {link = 'NvimTreeGitDirty'},
  NvimTreeFileMerge = {link = 'NvimTreeGitMerge'},
  NvimTreeFileNew = {link = 'NvimTreeGitNew'},
  NvimTreeFileRenamed = {link = 'NvimTreeGitRenamed'},
  NvimTreeFileStaged = {link = 'NvimTreeGitStaged'},
  NvimTreeFolderName = {link = 'Directory'},
  NvimTreeNormal = {link = 'Normal'},
  NvimTreePopup = {link = 'Normal'},
  NvimTreeVertSplit = {link = 'VertSplit'},
  NvimUnaryMinus = {link = 'NvimUnaryOperator'},
  NvimUnaryOperator = {link = 'NvimOperator'},
  NvimUnaryPlus = {link = 'NvimUnaryOperator'},
  Operator   = {link = 'Statement'},
  PreCondit  = {link = 'PreProc'},
  QuickFixLine = {link = 'Search'},
  Repeat     = {link = 'Statement'},
  SpecialChar = {link = 'Special'},
  SpecialComment = {link = 'Special'},
  StorageClass = {link = 'Type'},
  String     = {link = 'Constant'},
  Structure  = {link = 'Type'},
  Substitute = {link = 'Search'},
  TSAnnotation = {link = 'PreProc'},
  TSAttribute = {link = 'PreProc'},
  TSBoolean  = {link = 'Boolean'},
  TSCharacter = {link = 'Character'},
  TSConditional = {link = 'Conditional'},
  TSConstBuiltin = {link = 'Special'},
  TSConstMacro = {link = 'Define'},
  TSConstant = {link = 'Constant'},
  TSConstructor = {link = 'Special'},
  TSDanger   = {link = 'WarningMsg'},
  TSException = {link = 'Exception'},
  TSField    = {link = 'Identifier'},
  TSFloat    = {link = 'Float'},
  TSFuncBuiltin = {link = 'Special'},
  TSFuncMacro = {link = 'Macro'},
  TSFunction = {link = 'Function'},
  TSInclude  = {link = 'Include'},
  TSKeyword  = {link = 'Keyword'},
  TSKeywordFunction = {link = 'Keyword'},
  TSKeywordOperator = {link = 'TSOperator'},
  TSLabel    = {link = 'Label'},
  TSLiteral  = {link = 'String'},
  TSMethod   = {link = 'Function'},
  TSNamespace = {link = 'Include'},
  TSNote     = {link = 'SpecialComment'},
  TSNumber   = {link = 'Number'},
  TSOperator = {link = 'Operator'},
  TSParameter = {link = 'Identifier'},
  TSParameterReference = {link = 'TSParameter'},
  TSProperty = {link = 'Identifier'},
  TSPunctBracket = {link = 'Delimiter'},
  TSPunctDelimiter = {link = 'Delimiter'},
  TSPunctSpecial = {link = 'Delimiter'},
  TSRepeat   = {link = 'Repeat'},
  TSString   = {link = 'String'},
  TSStringEscape = {link = 'SpecialChar'},
  TSStringRegex = {link = 'String'},
  TSSymbol   = {link = 'Identifier'},
  TSTag      = {link = 'Label'},
  TSTagDelimiter = {link = 'Delimiter'},
  TSText     = {link = 'TSNone'},
  TSTitle    = {link = 'Title'},
  TSType     = {link = 'Type'},
  TSTypeBuiltin = {link = 'Type'},
  TSURI      = {link = 'Underlined'},
  TSVariableBuiltin = {link = 'Special'},
  TSWarning  = {link = 'Todo'},
  Tag        = {link = 'Special'},
  TelescopeBorder = {link = 'TelescopeNormal'},
  TelescopeMatching = {link = 'Special'},
  TelescopeMultiSelection = {link = 'Type'},
  TelescopeNormal = {link = 'Normal'},
  TelescopePreviewBlock = {link = 'Constant'},
  TelescopePreviewBorder = {link = 'TelescopeBorder'},
  TelescopePreviewCharDev = {link = 'Constant'},
  TelescopePreviewDate = {link = 'Directory'},
  TelescopePreviewDirectory = {link = 'Directory'},
  TelescopePreviewExecute = {link = 'String'},
  TelescopePreviewGroup = {link = 'Constant'},
  TelescopePreviewHyphen = {link = 'NonText'},
  TelescopePreviewLine = {link = 'Visual'},
  TelescopePreviewLink = {link = 'Special'},
  TelescopePreviewMatch = {link = 'Search'},
  TelescopePreviewNormal = {link = 'Normal'},
  TelescopePreviewPipe = {link = 'Constant'},
  TelescopePreviewRead = {link = 'Constant'},
  TelescopePreviewSize = {link = 'String'},
  TelescopePreviewSocket = {link = 'Statement'},
  TelescopePreviewSticky = {link = 'Keyword'},
  TelescopePreviewUser = {link = 'Constant'},
  TelescopePreviewWrite = {link = 'Statement'},
  TelescopePromptBorder = {link = 'TelescopeBorder'},
  TelescopePromptPrefix = {link = 'Identifier'},
  TelescopeResultsBorder = {link = 'TelescopeBorder'},
  TelescopeResultsClass = {link = 'Function'},
  TelescopeResultsComment = {link = 'Comment'},
  TelescopeResultsConstant = {link = 'Constant'},
  TelescopeResultsDiffAdd = {link = 'DiffAdd'},
  TelescopeResultsDiffChange = {link = 'DiffChange'},
  TelescopeResultsDiffDelete = {link = 'DiffDelete'},
  TelescopeResultsField = {link = 'Function'},
  TelescopeResultsFunction = {link = 'Function'},
  TelescopeResultsIdentifier = {link = 'Identifier'},
  TelescopeResultsLineNr = {link = 'LineNr'},
  TelescopeResultsMethod = {link = 'Method'},
  TelescopeResultsNumber = {link = 'Number'},
  TelescopeResultsOperator = {link = 'Operator'},
  TelescopeResultsSpecialComment = {link = 'SpecialComment'},
  TelescopeResultsStruct = {link = 'Struct'},
  TelescopeResultsVariable = {link = 'SpecialChar'},
  TelescopeSelection = {link = 'Visual'},
  TelescopeSelectionCaret = {link = 'TelescopeSelection'},
  Typedef    = {link = 'Type'},
  Whitespace = {link = 'NonText'},
  luaBraceError = {link = 'Error'},
  luaComment = {link = 'Comment'},
  luaCond    = {link = 'Conditional'},
  luaConstant = {link = 'Constant'},
  luaElse    = {link = 'Conditional'},
  luaError   = {link = 'Error'},
  luaFor     = {link = 'Repeat'},
  luaFunc    = {link = 'Identifier'},
  luaFunction = {link = 'Function'},
  luaIn      = {link = 'Operator'},
  luaLabel   = {link = 'Label'},
  luaNumber  = {link = 'Number'},
  luaOperator = {link = 'Operator'},
  luaParenError = {link = 'Error'},
  luaRepeat  = {link = 'Repeat'},
  luaSpecial = {link = 'SpecialChar'},
  luaStatement = {link = 'Statement'},
  luaString  = {link = 'String'},
  luaString2 = {link = 'String'},
  luaTable   = {link = 'Structure'},
  luaTodo    = {link = 'Todo'},
  nvimAutoEvent = {link = 'vimAutoEvent'},
  nvimHLGroup = {link = 'vimHLGroup'},
  nvimMap    = {link = 'vimMap'},
  nvimUnmap  = {link = 'vimUnmap'},
  vimAbb     = {link = 'vimCommand'},
  vimAddress = {link = 'vimMark'},
  vimAuHighlight = {link = 'vimHighlight'},
  vimAugroupError = {link = 'vimError'},
  vimAugroupKey = {link = 'vimCommand'},
  vimAutoCmd = {link = 'vimCommand'},
  vimAutoCmdOpt = {link = 'vimOption'},
  vimAutoEvent = {link = 'Type'},
  vimAutoSet = {link = 'vimCommand'},
  vimBehave  = {link = 'vimCommand'},
  vimBehaveError = {link = 'vimError'},
  vimBehaveModel = {link = 'vimBehave'},
  vimBracket = {link = 'Delimiter'},
  vimBufnrWarn = {link = 'vimWarn'},
  vimCmplxRepeat = {link = 'SpecialChar'},
  vimCollClassErr = {link = 'vimError'},
  vimCommand = {link = 'Statement'},
  vimComment = {link = 'Comment'},
  vimCommentString = {link = 'vimString'},
  vimCommentTitle = {link = 'PreProc'},
  vimCondHL  = {link = 'vimCommand'},
  vimContinue = {link = 'Special'},
  vimCtrlChar = {link = 'SpecialChar'},
  vimEchoHL  = {link = 'vimCommand'},
  vimEchoHLNone = {link = 'vimGroup'},
  vimElseIfErr = {link = 'Error'},
  vimElseif  = {link = 'vimCondHL'},
  vimEmbedError = {link = 'Normal'},
  vimEnvvar  = {link = 'PreProc'},
  vimErrSetting = {link = 'vimError'},
  vimError   = {link = 'Error'},
  vimFBVar   = {link = 'vimVar'},
  vimFTCmd   = {link = 'vimCommand'},
  vimFTError = {link = 'vimError'},
  vimFTOption = {link = 'vimSynType'},
  vimFgBgAttrib = {link = 'vimHiAttrib'},
  vimFold    = {link = 'Folded'},
  vimFunc    = {link = 'vimError'},
  vimFuncKey = {link = 'vimCommand'},
  vimFuncName = {link = 'Function'},
  vimFuncSID = {link = 'Special'},
  vimFuncVar = {link = 'Identifier'},
  vimFunctionError = {link = 'vimError'},
  vimGroup   = {link = 'Type'},
  vimGroupAdd = {link = 'vimSynOption'},
  vimGroupName = {link = 'vimGroup'},
  vimGroupRem = {link = 'vimSynOption'},
  vimGroupSpecial = {link = 'Special'},
  vimHLGroup = {link = 'vimGroup'},
  vimHLMod   = {link = 'PreProc'},
  vimHiAttrib = {link = 'PreProc'},
  vimHiAttribList = {link = 'vimError'},
  vimHiBlend = {link = 'vimHiTerm'},
  vimHiCTerm = {link = 'vimHiTerm'},
  vimHiClear = {link = 'vimHighlight'},
  vimHiCtermError = {link = 'vimError'},
  vimHiCtermFgBg = {link = 'vimHiTerm'},
  vimHiGroup = {link = 'vimGroupName'},
  vimHiGui   = {link = 'vimHiTerm'},
  vimHiGuiFgBg = {link = 'vimHiTerm'},
  vimHiGuiFont = {link = 'vimHiTerm'},
  vimHiGuiRgb = {link = 'vimNumber'},
  vimHiKeyError = {link = 'vimError'},
  vimHiNmbr  = {link = 'Number'},
  vimHiStartStop = {link = 'vimHiTerm'},
  vimHiTerm  = {link = 'Type'},
  vimHighlight = {link = 'vimCommand'},
  vimInsert  = {link = 'vimString'},
  vimIskSep  = {link = 'Delimiter'},
  vimKeyCode = {link = 'vimSpecFile'},
  vimKeyCodeError = {link = 'vimError'},
  vimKeyword = {link = 'Statement'},
  vimLet     = {link = 'vimCommand'},
  vimLineComment = {link = 'vimComment'},
  vimMap     = {link = 'vimCommand'},
  vimMapBang = {link = 'vimCommand'},
  vimMapMod  = {link = 'vimBracket'},
  vimMapModErr = {link = 'vimError'},
  vimMapModKey = {link = 'vimFuncSID'},
  vimMark    = {link = 'Number'},
  vimMarkNumber = {link = 'vimNumber'},
  vimMenuMod = {link = 'vimMapMod'},
  vimMenuName = {link = 'PreProc'},
  vimMenuNameMore = {link = 'vimMenuName'},
  vimMtchComment = {link = 'vimComment'},
  vimNorm    = {link = 'vimCommand'},
  vimNotFunc = {link = 'vimCommand'},
  vimNotPatSep = {link = 'vimString'},
  vimNotation = {link = 'Special'},
  vimNumber  = {link = 'Number'},
  vimOper    = {link = 'Operator'},
  vimOperError = {link = 'Error'},
  vimOption  = {link = 'PreProc'},
  vimParenSep = {link = 'Delimiter'},
  vimPatSep  = {link = 'SpecialChar'},
  vimPatSepErr = {link = 'vimError'},
  vimPatSepR = {link = 'vimPatSep'},
  vimPatSepZ = {link = 'vimPatSep'},
  vimPatSepZone = {link = 'vimString'},
  vimPattern = {link = 'Type'},
  vimPlainMark = {link = 'vimMark'},
  vimPlainRegister = {link = 'vimRegister'},
  vimRegister = {link = 'SpecialChar'},
  vimScriptDelim = {link = 'Comment'},
  vimSearch  = {link = 'vimString'},
  vimSearchDelim = {link = 'Statement'},
  vimSep     = {link = 'Delimiter'},
  vimSetMod  = {link = 'vimOption'},
  vimSetSep  = {link = 'Statement'},
  vimSetString = {link = 'vimString'},
  vimSpecFile = {link = 'Identifier'},
  vimSpecFileMod = {link = 'vimSpecFile'},
  vimSpecial = {link = 'Type'},
  vimStatement = {link = 'Statement'},
  vimString  = {link = 'String'},
  vimStringCont = {link = 'vimString'},
  vimStringEnd = {link = 'vimString'},
  vimSubst   = {link = 'vimCommand'},
  vimSubst1  = {link = 'vimSubst'},
  vimSubstDelim = {link = 'Delimiter'},
  vimSubstFlagErr = {link = 'vimError'},
  vimSubstFlags = {link = 'Special'},
  vimSubstSubstr = {link = 'SpecialChar'},
  vimSubstTwoBS = {link = 'vimString'},
  vimSynCase = {link = 'Type'},
  vimSynCaseError = {link = 'vimError'},
  vimSynContains = {link = 'vimSynOption'},
  vimSynError = {link = 'Error'},
  vimSynKeyContainedin = {link = 'vimSynContains'},
  vimSynKeyOpt = {link = 'vimSynOption'},
  vimSynMtchGrp = {link = 'vimSynOption'},
  vimSynMtchOpt = {link = 'vimSynOption'},
  vimSynNextgroup = {link = 'vimSynOption'},
  vimSynNotPatRange = {link = 'vimSynRegPat'},
  vimSynOption = {link = 'Special'},
  vimSynPatRange = {link = 'vimString'},
  vimSynReg  = {link = 'Type'},
  vimSynRegOpt = {link = 'vimSynOption'},
  vimSynRegPat = {link = 'vimString'},
  vimSynType = {link = 'vimSpecial'},
  vimSyncC   = {link = 'Type'},
  vimSyncError = {link = 'Error'},
  vimSyncGroup = {link = 'vimGroupName'},
  vimSyncGroupName = {link = 'vimGroupName'},
  vimSyncKey = {link = 'Type'},
  vimSyncNone = {link = 'Type'},
  vimSyntax  = {link = 'vimCommand'},
  vimTodo    = {link = 'Todo'},
  vimUnmap   = {link = 'vimMap'},
  vimUserAttrb = {link = 'vimSpecial'},
  vimUserAttrbCmplt = {link = 'vimSpecial'},
  vimUserAttrbCmpltFunc = {link = 'Special'},
  vimUserAttrbError = {link = 'Error'},
  vimUserAttrbKey = {link = 'vimOption'},
  vimUserCmdError = {link = 'Error'},
  vimUserCommand = {link = 'vimCommand'},
  vimUserFunc = {link = 'Normal'},
  vimVar     = {link = 'Identifier'},
  vimWarn    = {link = 'WarningMsg'},
}

return highlights