abbr "arts"="art serve --port 2323"
abbr "brewmeup"="brew update -v; brew upgrade -v; brew cleanup -s -v; brew doctor -v"
abbr "cf"="\$HOME/dotfiles/scripts/cf.sh"
abbr "cp"="cp -iv"
abbr "cwd"="basename \$PWD"
abbr "dcu"="docker compose up"
abbr "f"="fossil"
abbr "got"="go test ./..."
abbr "jst"="jsr test -- run"
abbr "head"="HEAD~1"
abbr "imix"="iex -S mix"
abbr "keyevent"="xev -event keyboard | grep -o -e '(keysym .*, .*)'"
abbr "lg"="lazygit"
abbr "lite"="litecli"
abbr "mkdir"="mkdir -pv"
abbr "mv"="mv -iv"
abbr "nv"="nvim"
# abbr "oc"="opencode"
abbr "pg"="pgrep"
abbr "pgn"="ps ax | grep ' [n]vim$'"
abbr "pk"="pkill"
abbr "sosh"="source \$XDG_CONFIG_HOME/zsh/.zshrc"
abbr "task"="./Taskfile"
abbr "tma"="tmux attach -t "
abbr "yeet"="rm -rf"

# git shortcuts
abbr g="git"
abbr gcm="git commit"
abbr gl="git l"
abbr gs="git status -s"
# git switch
abbr gsw="git switch"
abbr grs="git reset"
abbr grh="git reset --soft head^"
# reset
# restore
