-- require('nvim-lightbulb').update_lightbulb {
--   sign = {
--     enabled = false,
--   },
--   float = {
--     enabled = true,
--     text = "💡",
--   },
--   virtual_text = {
--     enabled = false,
--     text = "💡",
--   },
-- }
vim.cmd [[autocmd CursorHold,CursorHoldI * lua require('nvim-lightbulb').update_lightbulb { sign = { enabled = false, }, float = { enabled = false, text = "💡", }, virtual_text = { enabled = true, text = "💡", }} ]]
